AllCops:
  TargetRubyVersion: 2.1
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/EvalWithLocation:
    Enabled: false
